name: VoidSurvival
version: 1.0
description: Small plugin to manage void survival things
depend: [WorldEdit, WorldGuard]
libraries:
  - com.sk89q.worldguard:worldguard-bukkit:7.0.14
  - com.sk89q.worldedit:worldedit-bukkit:7.3.17